package GameModule;


/**
* GameModule/Bool.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/java/idl/GameService.idl
* Thursday, May 29, 2025 1:24:56 PM SGT
*/

public class Bool implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static GameModule.Bool[] __array = new GameModule.Bool [__size];

  public static final int _BOOL_FALSE = 0;
  public static final GameModule.Bool BOOL_FALSE = new GameModule.Bool(_BOOL_FALSE);
  public static final int _BOOL_TRUE = 1;
  public static final GameModule.Bool BOOL_TRUE = new GameModule.Bool(_BOOL_TRUE);

  public int value ()
  {
    return __value;
  }

  public static GameModule.Bool from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected Bool (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class Bool
