package GameModule;


/**
* GameModule/GameServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/java/idl/GameService.idl
* Thursday, May 29, 2025 1:24:56 PM SGT
*/

public interface GameServiceOperations 
{

  //client
  GameModule.Bool login (String username, String password) throws GameModule.AlreadyLoggedInException;
  void logout (String username);
  String startGame (String username);
  GameModule.Bool sendGuess (String username, char letter);
  void finishRound (String username, int clientRemainingTime, boolean guessedWord);
  String viewLeaderboard ();
  String getMaskedWord (String username);

  // Admin
  GameModule.Bool createPlayer (String username, String password);
  GameModule.Bool deletePlayer (String username);
  GameModule.Bool updatePlayerPassword (String username, String newPassword);
  GameModule.Bool updateSettings (int waitingTime, int roundTime);
  GameModule.Bool updatePlayerUsername (String username, String newUsername);
  GameModule.Bool updatePlayerWins (String username, int wins);
  String viewPlayers ();

  //server
  int getRoundTime ();
  int getWaitingTime ();
  int getRemainingTime (String username);
  int getIncorrectGuesses (String username);
  void endGameSession (String username);
  int getCurrentRound (String username);
  int getPlayerWins (String username);
  GameModule.Bool startNewRound (String username);
  GameModule.Bool isRoundOver (String username);
  GameModule.Bool isGameSessionOver (String username);
  String getGameSessionResult (String username);
  GameModule.GameStateDTO getGameState (String username);

  // Explicit cleanup after game session ends
  void cleanupPlayerSession (String username);

  // Admin word management
  GameModule.Bool addWord (String word);
  GameModule.Bool updateWord (String oldWord, String newWord);
  GameModule.Bool deleteWord (String word);
  String[] getAllWords ();
  GameModule.SystemStatisticsDTO getSystemStatistics ();
  GameModule.LeaderboardEntryDTO[] getLeaderboardEntries ();

  // Multiplayer mode
  String startMultiplayerGame (String username);
  String getMultiplayerLobbyState (String username);
  GameModule.Bool sendMultiplayerGuess (String username, char letter);
  GameModule.Bool startMultiplayerNextRound (String username);

  // Match history (returns JSON)
  String getMatchHistory (String username);
  String getMatchDetails (String gameId);

  // Single Player Match History
  String getSinglePlayerMatchHistory (String username);
  String getSinglePlayerMatchDetails (String gameId);
} // interface GameServiceOperations
