package GameModule;


/**
* GameModule/LoginResponse.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/java/idl/GameService.idl
* Sunday, June 15, 2025 11:43:01 PM SGT
*/

public final class LoginResponse implements org.omg.CORBA.portable.IDLEntity
{
  public GameModule.Bool success = null;
  public String sessionId = null;

  public LoginResponse ()
  {
  } // ctor

  public LoginResponse (GameModule.Bool _success, String _sessionId)
  {
    success = _success;
    sessionId = _sessionId;
  } // ctor

} // class LoginResponse
