# DO NOT EDIT THIS FILE!
#
# Python module GameModule__POA generated by omniidl

import omniORB
omniORB.updateModule("GameModule__POA")

# ** 1. Stub files contributing to this module
import GameService_idl

# ** 2. Sub-modules

# ** 3. End
