# DO NOT EDIT THIS FILE!
#
# Python module GameModule generated by omniidl

import omniORB
omniORB.updateModule("GameModule")

# ** 1. Stub files contributing to this module
import GameService_idl

# ** 2. Sub-modules

# ** 3. End
