# Python stubs generated by omniidl from LoginService.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "LoginModule"
#
__name__ = "LoginModule"
_0_LoginModule = omniORB.openModule("LoginModule", r"LoginService.idl")
_0_LoginModule__POA = omniORB.openModule("LoginModule__POA", r"LoginService.idl")


# exception AlreadyLoggedInException
_0_LoginModule.AlreadyLoggedInException = omniORB.newEmptyClass()
class AlreadyLoggedInException (CORBA.UserException):
    _NP_RepositoryId = "IDL:LoginModule/AlreadyLoggedInException:1.0"

    def __init__(self, message):
        CORBA.UserException.__init__(self, message)
        self.message = message

_0_LoginModule.AlreadyLoggedInException = AlreadyLoggedInException
_0_LoginModule._d_AlreadyLoggedInException  = (omniORB.tcInternal.tv_except, AlreadyLoggedInException, AlreadyLoggedInException._NP_RepositoryId, "AlreadyLoggedInException", "message", (omniORB.tcInternal.tv_string,0))
_0_LoginModule._tc_AlreadyLoggedInException = omniORB.tcInternal.createTypeCode(_0_LoginModule._d_AlreadyLoggedInException)
omniORB.registerType(AlreadyLoggedInException._NP_RepositoryId, _0_LoginModule._d_AlreadyLoggedInException, _0_LoginModule._tc_AlreadyLoggedInException)
del AlreadyLoggedInException

# enum Bool
_0_LoginModule.BOOL_FALSE = omniORB.EnumItem("BOOL_FALSE", 0)
_0_LoginModule.BOOL_TRUE = omniORB.EnumItem("BOOL_TRUE", 1)
_0_LoginModule.Bool = omniORB.Enum("IDL:LoginModule/Bool:1.0", (_0_LoginModule.BOOL_FALSE, _0_LoginModule.BOOL_TRUE,))

_0_LoginModule._d_Bool  = (omniORB.tcInternal.tv_enum, _0_LoginModule.Bool._NP_RepositoryId, "Bool", _0_LoginModule.Bool._items)
_0_LoginModule._tc_Bool = omniORB.tcInternal.createTypeCode(_0_LoginModule._d_Bool)
omniORB.registerType(_0_LoginModule.Bool._NP_RepositoryId, _0_LoginModule._d_Bool, _0_LoginModule._tc_Bool)

# struct LoginResponse
_0_LoginModule.LoginResponse = omniORB.newEmptyClass()
class LoginResponse (omniORB.StructBase):
    _NP_RepositoryId = "IDL:LoginModule/LoginResponse:1.0"

    def __init__(self, success, sessionId):
        self.success = success
        self.sessionId = sessionId

_0_LoginModule.LoginResponse = LoginResponse
_0_LoginModule._d_LoginResponse  = (omniORB.tcInternal.tv_struct, LoginResponse, LoginResponse._NP_RepositoryId, "LoginResponse", "success", omniORB.typeMapping["IDL:LoginModule/Bool:1.0"], "sessionId", (omniORB.tcInternal.tv_string,0))
_0_LoginModule._tc_LoginResponse = omniORB.tcInternal.createTypeCode(_0_LoginModule._d_LoginResponse)
omniORB.registerType(LoginResponse._NP_RepositoryId, _0_LoginModule._d_LoginResponse, _0_LoginModule._tc_LoginResponse)
del LoginResponse

# interface LoginService
_0_LoginModule._d_LoginService = (omniORB.tcInternal.tv_objref, "IDL:LoginModule/LoginService:1.0", "LoginService")
omniORB.typeMapping["IDL:LoginModule/LoginService:1.0"] = _0_LoginModule._d_LoginService
_0_LoginModule.LoginService = omniORB.newEmptyClass()
class LoginService :
    _NP_RepositoryId = _0_LoginModule._d_LoginService[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_LoginModule.LoginService = LoginService
_0_LoginModule._tc_LoginService = omniORB.tcInternal.createTypeCode(_0_LoginModule._d_LoginService)
omniORB.registerType(LoginService._NP_RepositoryId, _0_LoginModule._d_LoginService, _0_LoginModule._tc_LoginService)

# LoginService operations and attributes
LoginService._d_loginWithSession = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (omniORB.typeMapping["IDL:LoginModule/LoginResponse:1.0"], ), {_0_LoginModule.AlreadyLoggedInException._NP_RepositoryId: _0_LoginModule._d_AlreadyLoggedInException})
LoginService._d_login = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (omniORB.typeMapping["IDL:LoginModule/Bool:1.0"], ), {_0_LoginModule.AlreadyLoggedInException._NP_RepositoryId: _0_LoginModule._d_AlreadyLoggedInException})
LoginService._d_logout = (((omniORB.tcInternal.tv_string,0), ), (), None)
LoginService._d_createPlayer = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (omniORB.typeMapping["IDL:LoginModule/Bool:1.0"], ), None)
LoginService._d_validateSession = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (omniORB.typeMapping["IDL:LoginModule/Bool:1.0"], ), None)
LoginService._d_checkSessionValid = (((omniORB.tcInternal.tv_string,0), ), (omniORB.typeMapping["IDL:LoginModule/Bool:1.0"], ), None)
LoginService._d_keepAlive = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (omniORB.typeMapping["IDL:LoginModule/Bool:1.0"], ), None)

# LoginService object reference
class _objref_LoginService (CORBA.Object):
    _NP_RepositoryId = LoginService._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def loginWithSession(self, *args):
        return self._obj.invoke("loginWithSession", _0_LoginModule.LoginService._d_loginWithSession, args)

    def login(self, *args):
        return self._obj.invoke("login", _0_LoginModule.LoginService._d_login, args)

    def logout(self, *args):
        return self._obj.invoke("logout", _0_LoginModule.LoginService._d_logout, args)

    def createPlayer(self, *args):
        return self._obj.invoke("createPlayer", _0_LoginModule.LoginService._d_createPlayer, args)

    def validateSession(self, *args):
        return self._obj.invoke("validateSession", _0_LoginModule.LoginService._d_validateSession, args)

    def checkSessionValid(self, *args):
        return self._obj.invoke("checkSessionValid", _0_LoginModule.LoginService._d_checkSessionValid, args)

    def keepAlive(self, *args):
        return self._obj.invoke("keepAlive", _0_LoginModule.LoginService._d_keepAlive, args)

omniORB.registerObjref(LoginService._NP_RepositoryId, _objref_LoginService)
_0_LoginModule._objref_LoginService = _objref_LoginService
del LoginService, _objref_LoginService

# LoginService skeleton
__name__ = "LoginModule__POA"
class LoginService (PortableServer.Servant):
    _NP_RepositoryId = _0_LoginModule.LoginService._NP_RepositoryId


    _omni_op_d = {"loginWithSession": _0_LoginModule.LoginService._d_loginWithSession, "login": _0_LoginModule.LoginService._d_login, "logout": _0_LoginModule.LoginService._d_logout, "createPlayer": _0_LoginModule.LoginService._d_createPlayer, "validateSession": _0_LoginModule.LoginService._d_validateSession, "checkSessionValid": _0_LoginModule.LoginService._d_checkSessionValid, "keepAlive": _0_LoginModule.LoginService._d_keepAlive}

LoginService._omni_skeleton = LoginService
_0_LoginModule__POA.LoginService = LoginService
omniORB.registerSkeleton(LoginService._NP_RepositoryId, LoginService)
del LoginService
__name__ = "LoginModule"

#
# End of module "LoginModule"
#
__name__ = "LoginService_idl"

_exported_modules = ( "LoginModule", )

# The end.
