package GameModule;


/**
* GameModule/AdminServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Monday, June 9, 2025 2:37:33 AM SGT
*/


// Admin-specific functionality
public abstract class AdminServicePOA extends org.omg.PortableServer.Servant
 implements GameModule.AdminServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("createPlayer", new java.lang.Integer (0));
    _methods.put ("deletePlayer", new java.lang.Integer (1));
    _methods.put ("updatePlayerPassword", new java.lang.Integer (2));
    _methods.put ("updateSettings", new java.lang.Integer (3));
    _methods.put ("updatePlayerUsername", new java.lang.Integer (4));
    _methods.put ("updatePlayerWins", new java.lang.Integer (5));
    _methods.put ("viewPlayers", new java.lang.Integer (6));
    _methods.put ("addWord", new java.lang.Integer (7));
    _methods.put ("updateWord", new java.lang.Integer (8));
    _methods.put ("deleteWord", new java.lang.Integer (9));
    _methods.put ("getAllWords", new java.lang.Integer (10));
    _methods.put ("getSystemStatistics", new java.lang.Integer (11));
    _methods.put ("getLeaderboardEntries", new java.lang.Integer (12));
    _methods.put ("login", new java.lang.Integer (13));
    _methods.put ("logout", new java.lang.Integer (14));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // Admin player management
       case 0:  // GameModule/AdminService/createPlayer
       {
         String username = in.read_string ();
         String password = in.read_string ();
         GameModule.Bool $result = null;
         $result = this.createPlayer (username, password);
         out = $rh.createReply();
         GameModule.BoolHelper.write (out, $result);
         break;
       }

       case 1:  // GameModule/AdminService/deletePlayer
       {
         String username = in.read_string ();
         GameModule.Bool $result = null;
         $result = this.deletePlayer (username);
         out = $rh.createReply();
         GameModule.BoolHelper.write (out, $result);
         break;
       }

       case 2:  // GameModule/AdminService/updatePlayerPassword
       {
         String username = in.read_string ();
         String newPassword = in.read_string ();
         GameModule.Bool $result = null;
         $result = this.updatePlayerPassword (username, newPassword);
         out = $rh.createReply();
         GameModule.BoolHelper.write (out, $result);
         break;
       }

       case 3:  // GameModule/AdminService/updateSettings
       {
         int waitingTime = in.read_long ();
         int roundTime = in.read_long ();
         GameModule.Bool $result = null;
         $result = this.updateSettings (waitingTime, roundTime);
         out = $rh.createReply();
         GameModule.BoolHelper.write (out, $result);
         break;
       }

       case 4:  // GameModule/AdminService/updatePlayerUsername
       {
         String username = in.read_string ();
         String newUsername = in.read_string ();
         GameModule.Bool $result = null;
         $result = this.updatePlayerUsername (username, newUsername);
         out = $rh.createReply();
         GameModule.BoolHelper.write (out, $result);
         break;
       }

       case 5:  // GameModule/AdminService/updatePlayerWins
       {
         String username = in.read_string ();
         int wins = in.read_long ();
         GameModule.Bool $result = null;
         $result = this.updatePlayerWins (username, wins);
         out = $rh.createReply();
         GameModule.BoolHelper.write (out, $result);
         break;
       }

       case 6:  // GameModule/AdminService/viewPlayers
       {
         String $result = null;
         $result = this.viewPlayers ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }


  // Admin word management
       case 7:  // GameModule/AdminService/addWord
       {
         String word = in.read_string ();
         GameModule.Bool $result = null;
         $result = this.addWord (word);
         out = $rh.createReply();
         GameModule.BoolHelper.write (out, $result);
         break;
       }

       case 8:  // GameModule/AdminService/updateWord
       {
         String oldWord = in.read_string ();
         String newWord = in.read_string ();
         GameModule.Bool $result = null;
         $result = this.updateWord (oldWord, newWord);
         out = $rh.createReply();
         GameModule.BoolHelper.write (out, $result);
         break;
       }

       case 9:  // GameModule/AdminService/deleteWord
       {
         String word = in.read_string ();
         GameModule.Bool $result = null;
         $result = this.deleteWord (word);
         out = $rh.createReply();
         GameModule.BoolHelper.write (out, $result);
         break;
       }

       case 10:  // GameModule/AdminService/getAllWords
       {
         String $result[] = null;
         $result = this.getAllWords ();
         out = $rh.createReply();
         GameModule.StringSeqHelper.write (out, $result);
         break;
       }


  // Admin statistics
       case 11:  // GameModule/AdminService/getSystemStatistics
       {
         GameModule.SystemStatisticsDTO $result = null;
         $result = this.getSystemStatistics ();
         out = $rh.createReply();
         GameModule.SystemStatisticsDTOHelper.write (out, $result);
         break;
       }

       case 12:  // GameModule/AdminService/getLeaderboardEntries
       {
         GameModule.LeaderboardEntryDTO $result[] = null;
         $result = this.getLeaderboardEntries ();
         out = $rh.createReply();
         GameModule.LeaderboardEntrySeqHelper.write (out, $result);
         break;
       }

       case 13:  // GameModule/CommonService/login
       {
         try {
           String username = in.read_string ();
           String password = in.read_string ();
           GameModule.Bool $result = null;
           $result = this.login (username, password);
           out = $rh.createReply();
           GameModule.BoolHelper.write (out, $result);
         } catch (GameModule.AlreadyLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           GameModule.AlreadyLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 14:  // GameModule/CommonService/logout
       {
         String username = in.read_string ();
         this.logout (username);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:GameModule/AdminService:1.0", 
    "IDL:GameModule/CommonService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public AdminService _this() 
  {
    return AdminServiceHelper.narrow(
    super._this_object());
  }

  public AdminService _this(org.omg.CORBA.ORB orb) 
  {
    return AdminServiceHelper.narrow(
    super._this_object(orb));
  }


} // class AdminServicePOA
