package GameModule;


/**
* GameModule/AdminService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Monday, June 9, 2025 2:37:33 AM SGT
*/


// Admin-specific functionality
public interface AdminService extends AdminServiceOperations, GameModule.CommonService, org.omg.CORBA.portable.IDLEntity 
{
} // interface AdminService
