package GameModule;

/**
* GameModule/AdminServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Monday, June 9, 2025 2:37:33 AM SGT
*/


// Admin-specific functionality
public final class AdminServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public GameModule.AdminService value = null;

  public AdminServiceHolder ()
  {
  }

  public AdminServiceHolder (GameModule.AdminService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameModule.AdminServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameModule.AdminServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameModule.AdminServiceHelper.type ();
  }

}
