package GameModule;


/**
* GameModule/AdminServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Monday, June 9, 2025 2:37:33 AM SGT
*/


// Admin-specific functionality
public interface AdminServiceOperations  extends GameModule.CommonServiceOperations
{

  // Admin player management
  GameModule.Bool createPlayer (String username, String password);
  GameModule.Bool deletePlayer (String username);
  GameModule.Bool updatePlayerPassword (String username, String newPassword);
  GameModule.Bool updateSettings (int waitingTime, int roundTime);
  GameModule.Bool updatePlayerUsername (String username, String newUsername);
  GameModule.Bool updatePlayerWins (String username, int wins);
  String viewPlayers ();

  // Admin word management
  GameModule.Bool addWord (String word);
  GameModule.Bool updateWord (String oldWord, String newWord);
  GameModule.Bool deleteWord (String word);
  String[] getAllWords ();

  // Admin statistics
  GameModule.SystemStatisticsDTO getSystemStatistics ();
  GameModule.LeaderboardEntryDTO[] getLeaderboardEntries ();
} // interface AdminServiceOperations
