package GameModule;

/**
* GameModule/AlreadyLoggedInExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
<<<<<<< HEAD
* from src/main/java/idl/GameService.idl
* Monday, May 12, 2025 5:24:30 PM SGT
=======
* from GameService.idl
* Tuesday, May 13, 2025 6:18:19 PM SGT
>>>>>>> main
*/

public final class AlreadyLoggedInExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public GameModule.AlreadyLoggedInException value = null;

  public AlreadyLoggedInExceptionHolder ()
  {
  }

  public AlreadyLoggedInExceptionHolder (GameModule.AlreadyLoggedInException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameModule.AlreadyLoggedInExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameModule.AlreadyLoggedInExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameModule.AlreadyLoggedInExceptionHelper.type ();
  }

}
