package GameModule;

/**
* GameModule/BoolHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Monday, June 16, 2025 5:48:05 PM SGT
*/

public final class BoolHolder implements org.omg.CORBA.portable.Streamable
{
  public GameModule.Bool value = null;

  public BoolHolder ()
  {
  }

  public BoolHolder (GameModule.Bool initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameModule.BoolHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameModule.BoolHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameModule.BoolHelper.type ();
  }

}
