package GameModule;


/**
* GameModule/CommonServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Monday, June 9, 2025 2:37:33 AM SGT
*/


// Common interface for both player and admin
public abstract class CommonServicePOA extends org.omg.PortableServer.Servant
 implements GameModule.CommonServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("login", new java.lang.Integer (0));
    _methods.put ("logout", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // GameModule/CommonService/login
       {
         try {
           String username = in.read_string ();
           String password = in.read_string ();
           GameModule.Bool $result = null;
           $result = this.login (username, password);
           out = $rh.createReply();
           GameModule.BoolHelper.write (out, $result);
         } catch (GameModule.AlreadyLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           GameModule.AlreadyLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // GameModule/CommonService/logout
       {
         String username = in.read_string ();
         this.logout (username);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:GameModule/CommonService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public CommonService _this() 
  {
    return CommonServiceHelper.narrow(
    super._this_object());
  }

  public CommonService _this(org.omg.CORBA.ORB orb) 
  {
    return CommonServiceHelper.narrow(
    super._this_object(orb));
  }


} // class CommonServicePOA
