package GameModule;


/**
* GameModule/CommonServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Monday, June 9, 2025 2:37:33 AM SGT
*/


// Common interface for both player and admin
public interface CommonServiceOperations 
{
  GameModule.Bool login (String username, String password) throws GameModule.AlreadyLoggedInException;
  void logout (String username);
} // interface CommonServiceOperations
