package GameModule;

/**
* GameModule/CommonServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Monday, June 9, 2025 2:37:33 AM SGT
*/


// Common interface for both player and admin
public final class CommonServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public GameModule.CommonService value = null;

  public CommonServiceHolder ()
  {
  }

  public CommonServiceHolder (GameModule.CommonService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameModule.CommonServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameModule.CommonServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameModule.CommonServiceHelper.type ();
  }

}
