package GameModule;


/**
* GameModule/GameServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Thursday, May 29, 2025 10:39:55 AM SGT
*/

public interface GameServiceOperations 
{
  boolean login (String username, String password) throws GameModule.AlreadyLoggedInException;
  void logout (String username);
  String startGame (String username);
  boolean sendGuess (String username, char letter);
  void finishRound (String username, int clientRemainingTime, boolean guessedWord);
  String viewLeaderboard ();
  String getMaskedWord (String username);

  // Admin
  boolean createPlayer (String username, String password);
  boolean deletePlayer (String username);
  boolean updatePlayerPassword (String username, String newPassword);
  boolean updateSettings (int waitingTime, int roundTime);
  boolean updatePlayerUsername (String username, String newUsername);
  boolean updatePlayerWins (String username, int wins);
  String viewPlayers ();

  //server
  int getRoundTime ();
  int getWaitingTime ();
  int getRemainingTime (String username);
  int getIncorrectGuesses (String username);
  void endGameSession (String username);
  int getCurrentRound (String username);
  int getPlayerWins (String username);
  boolean startNewRound (String username);
  boolean isRoundOver (String username);
  boolean isGameSessionOver (String username);
  String getGameSessionResult (String username);
  GameModule.GameStateDTO getGameState (String username);

  // Explicit cleanup after game session ends
  void cleanupPlayerSession (String username);

  // Admin word management
  boolean addWord (String word);
  boolean updateWord (String oldWord, String newWord);
  boolean deleteWord (String word);
  String[] getAllWords ();
  GameModule.SystemStatisticsDTO getSystemStatistics ();
  GameModule.LeaderboardEntryDTO[] getLeaderboardEntries ();

  // Multiplayer mode
  String startMultiplayerGame (String username);
  String getMultiplayerLobbyState (String username);
  boolean sendMultiplayerGuess (String username, char letter);
  boolean startMultiplayerNextRound (String username);

  // Match history (returns JSON)
  String getMatchHistory (String username);
  String getMatchDetails (String gameId);

  // Single Player Match History
  String getSinglePlayerMatchHistory (String username);
  String getSinglePlayerMatchDetails (String gameId);
} // interface GameServiceOperations
