package GameModule;

/**
* GameModule/GameStateDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
<<<<<<< HEAD
* from src/main/java/idl/GameService.idl
* Monday, May 12, 2025 5:24:30 PM SGT
=======
* from GameService.idl
* Tuesday, May 13, 2025 6:18:19 PM SGT
>>>>>>> main
*/

public final class GameStateDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public GameModule.GameStateDTO value = null;

  public GameStateDTOHolder ()
  {
  }

  public GameStateDTOHolder (GameModule.GameStateDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameModule.GameStateDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameModule.GameStateDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameModule.GameStateDTOHelper.type ();
  }

}
