package GameModule;

/**
* GameModule/GameStateDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Thursday, May 15, 2025 9:07:00 AM SGT
*/

public final class GameStateDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public GameModule.GameStateDTO value = null;

  public GameStateDTOHolder ()
  {
  }

  public GameStateDTOHolder (GameModule.GameStateDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameModule.GameStateDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameModule.GameStateDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameModule.GameStateDTOHelper.type ();
  }

}
