package GameModule;


/**
* GameModule/GameStateDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Sunday, June 15, 2025 2:34:42 AM SGT
*/

public final class GameStateDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String maskedWord = null;
  public int incorrectGuesses = (int)0;
  public int currentRound = (int)0;
  public int totalRounds = (int)0;
  public int playerWins = (int)0;
  public GameModule.Bool roundOver = null;
  public GameModule.Bool gameOver = null;
  public String sessionResult = null;
  public int remainingTime = (int)0;
  public String roundWinner = null;
  public int finishedTime = (int)0;
  public String opponentUsername = null;

  public GameStateDTO ()
  {
  } // ctor

  public GameStateDTO (String _maskedWord, int _incorrectGuesses, int _currentRound, int _totalRounds, int _playerWins, GameModule.Bool _roundOver, GameModule.Bool _gameOver, String _sessionResult, int _remainingTime, String _roundWinner, int _finishedTime, String _opponentUsername)
  {
    maskedWord = _maskedWord;
    incorrectGuesses = _incorrectGuesses;
    currentRound = _currentRound;
    totalRounds = _totalRounds;
    playerWins = _playerWins;
    roundOver = _roundOver;
    gameOver = _gameOver;
    sessionResult = _sessionResult;
    remainingTime = _remainingTime;
    roundWinner = _roundWinner;
    finishedTime = _finishedTime;
    opponentUsername = _opponentUsername;
  } // ctor

} // class GameStateDTO
