package GameModule;


/**
* GameModule/GameService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/java/idl/GameService.idl
* Monday, June 9, 2025 5:50:39 PM SGT
*/

public interface GameService extends GameServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GameService
