package GameModule;


/**
* GameModule/GameServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
<<<<<<< HEAD
* from src/main/java/idl/GameService.idl
* Monday, May 12, 2025 5:24:30 PM SGT
=======
* from GameService.idl
* Tuesday, May 13, 2025 6:18:19 PM SGT
>>>>>>> main
*/

public interface GameServiceOperations 
{
  boolean login (String username, String password) throws GameModule.AlreadyLoggedInException;
  void logout (String username);
  String startGame (String username);
  boolean sendGuess (String username, char letter);
  void finishRound (String username, int clientRemainingTime, boolean guessedWord);
  String viewLeaderboard ();
  String getMaskedWord (String username);

  // Admin
  boolean createPlayer (String username, String password);
  boolean deletePlayer (String username);
  boolean updatePlayerPassword (String username, String newPassword);
  boolean updateSettings (int waitingTime, int roundTime);
  boolean updatePlayerUsername (String username, String newUsername);
  boolean updatePlayerWins (String username, int wins);
  String viewPlayers ();

  //server
  int getRoundTime ();
  int getWaitingTime ();
  int getRemainingTime (String username);
  int getIncorrectGuesses (String username);
  void endGameSession (String username);
  int getCurrentRound (String username);
  int getPlayerWins (String username);
  boolean startNewRound (String username);
  boolean isRoundOver (String username);
  boolean isGameSessionOver (String username);
  GameModule.GameStateDTO getGameState (String username);
<<<<<<< HEAD
=======

  // Admin word management
  boolean addWord (String word);
  boolean updateWord (String oldWord, String newWord);
  boolean deleteWord (String word);
  String[] getAllWords ();
>>>>>>> main
} // interface GameServiceOperations
