package GameModule;


/**
* GameModule/GameStateDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Tuesday, May 13, 2025 8:11:36 PM SGT
*/

public final class GameStateDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String maskedWord = null;
  public int incorrectGuesses = (int)0;
  public int currentRound = (int)0;
  public int totalRounds = (int)0;
  public int playerWins = (int)0;
  public boolean roundOver = false;
  public boolean gameOver = false;
  public String sessionResult = null;
  public int remainingTime = (int)0;
  public String roundWinner = null;
  public int finishedTime = (int)0;

  public GameStateDTO ()
  {
  } // ctor

  public GameStateDTO (String _maskedWord, int _incorrectGuesses, int _currentRound, int _totalRounds, int _playerWins, boolean _roundOver, boolean _gameOver, String _sessionResult, int _remainingTime, String _roundWinner, int _finishedTime)
  {
    maskedWord = _maskedWord;
    incorrectGuesses = _incorrectGuesses;
    currentRound = _currentRound;
    totalRounds = _totalRounds;
    playerWins = _playerWins;
    roundOver = _roundOver;
    gameOver = _gameOver;
    sessionResult = _sessionResult;
    remainingTime = _remainingTime;
    roundWinner = _roundWinner;
    finishedTime = _finishedTime;
  } // ctor

} // class GameStateDTO
