package GameModule;


/**
* GameModule/LeaderboardEntryDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/java/idl/GameService.idl
* Friday, June 27, 2025 9:12:46 PM CST
*/

public final class LeaderboardEntryDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String username = null;
  public int wins = (int)0;

  public LeaderboardEntryDTO ()
  {
  } // ctor

  public LeaderboardEntryDTO (String _username, int _wins)
  {
    username = _username;
    wins = _wins;
  } // ctor

} // class LeaderboardEntryDTO
