package GameModule;

/**
* GameModule/LeaderboardEntryDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Monday, June 16, 2025 5:48:05 PM SGT
*/

public final class LeaderboardEntryDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public GameModule.LeaderboardEntryDTO value = null;

  public LeaderboardEntryDTOHolder ()
  {
  }

  public LeaderboardEntryDTOHolder (GameModule.LeaderboardEntryDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameModule.LeaderboardEntryDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameModule.LeaderboardEntryDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameModule.LeaderboardEntryDTOHelper.type ();
  }

}
