package GameModule;

/**
* GameModule/LoginResponseHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Monday, June 16, 2025 5:48:05 PM SGT
*/

public final class LoginResponseHolder implements org.omg.CORBA.portable.Streamable
{
  public GameModule.LoginResponse value = null;

  public LoginResponseHolder ()
  {
  }

  public LoginResponseHolder (GameModule.LoginResponse initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameModule.LoginResponseHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameModule.LoginResponseHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameModule.LoginResponseHelper.type ();
  }

}
