package GameModule;


/**
* GameModule/LoginResponseHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Monday, June 16, 2025 5:48:05 PM SGT
*/

abstract public class LoginResponseHelper
{
  private static String  _id = "IDL:GameModule/LoginResponse:1.0";

  public static void insert (org.omg.CORBA.Any a, GameModule.LoginResponse that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static GameModule.LoginResponse extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = GameModule.BoolHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "success",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "sessionId",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (GameModule.LoginResponseHelper.id (), "LoginResponse", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static GameModule.LoginResponse read (org.omg.CORBA.portable.InputStream istream)
  {
    GameModule.LoginResponse value = new GameModule.LoginResponse ();
    value.success = GameModule.BoolHelper.read (istream);
    value.sessionId = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, GameModule.LoginResponse value)
  {
    GameModule.BoolHelper.write (ostream, value.success);
    ostream.write_string (value.sessionId);
  }

}
