package GameModule;


/**
* GameModule/PlayerService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Monday, June 9, 2025 2:37:33 AM SGT
*/


// Player-specific functionality
public interface PlayerService extends PlayerServiceOperations, GameModule.CommonService, org.omg.CORBA.portable.IDLEntity 
{
} // interface PlayerService
