package GameModule;

/**
* GameModule/PlayerServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Monday, June 9, 2025 2:37:33 AM SGT
*/


// Player-specific functionality
public final class PlayerServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public GameModule.PlayerService value = null;

  public PlayerServiceHolder ()
  {
  }

  public PlayerServiceHolder (GameModule.PlayerService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameModule.PlayerServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameModule.PlayerServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameModule.PlayerServiceHelper.type ();
  }

}
