package GameModule;


/**
* GameModule/PlayerServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Monday, June 9, 2025 2:37:33 AM SGT
*/


// Player-specific functionality
public abstract class PlayerServicePOA extends org.omg.PortableServer.Servant
 implements GameModule.PlayerServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("startGame", new java.lang.Integer (0));
    _methods.put ("sendGuess", new java.lang.Integer (1));
    _methods.put ("finishRound", new java.lang.Integer (2));
    _methods.put ("viewLeaderboard", new java.lang.Integer (3));
    _methods.put ("getMaskedWord", new java.lang.Integer (4));
    _methods.put ("getRoundTime", new java.lang.Integer (5));
    _methods.put ("getWaitingTime", new java.lang.Integer (6));
    _methods.put ("getRemainingTime", new java.lang.Integer (7));
    _methods.put ("getIncorrectGuesses", new java.lang.Integer (8));
    _methods.put ("endGameSession", new java.lang.Integer (9));
    _methods.put ("getCurrentRound", new java.lang.Integer (10));
    _methods.put ("getPlayerWins", new java.lang.Integer (11));
    _methods.put ("startNewRound", new java.lang.Integer (12));
    _methods.put ("isRoundOver", new java.lang.Integer (13));
    _methods.put ("isGameSessionOver", new java.lang.Integer (14));
    _methods.put ("getGameSessionResult", new java.lang.Integer (15));
    _methods.put ("getGameState", new java.lang.Integer (16));
    _methods.put ("cleanupPlayerSession", new java.lang.Integer (17));
    _methods.put ("startMultiplayerGame", new java.lang.Integer (18));
    _methods.put ("getMultiplayerLobbyState", new java.lang.Integer (19));
    _methods.put ("sendMultiplayerGuess", new java.lang.Integer (20));
    _methods.put ("startMultiplayerNextRound", new java.lang.Integer (21));
    _methods.put ("getMatchHistory", new java.lang.Integer (22));
    _methods.put ("getMatchDetails", new java.lang.Integer (23));
    _methods.put ("getSinglePlayerMatchHistory", new java.lang.Integer (24));
    _methods.put ("getSinglePlayerMatchDetails", new java.lang.Integer (25));
    _methods.put ("playerReadyForFirstRound", new java.lang.Integer (26));
    _methods.put ("leaveMultiplayerGame", new java.lang.Integer (27));
    _methods.put ("getLeaderboardEntries", new java.lang.Integer (28));
    _methods.put ("login", new java.lang.Integer (29));
    _methods.put ("logout", new java.lang.Integer (30));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // GameModule/PlayerService/startGame
       {
         String username = in.read_string ();
         String $result = null;
         $result = this.startGame (username);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // GameModule/PlayerService/sendGuess
       {
         String username = in.read_string ();
         char letter = in.read_char ();
         GameModule.Bool $result = null;
         $result = this.sendGuess (username, letter);
         out = $rh.createReply();
         GameModule.BoolHelper.write (out, $result);
         break;
       }

       case 2:  // GameModule/PlayerService/finishRound
       {
         String username = in.read_string ();
         int clientRemainingTime = in.read_long ();
         GameModule.Bool guessedWord = GameModule.BoolHelper.read (in);
         this.finishRound (username, clientRemainingTime, guessedWord);
         out = $rh.createReply();
         break;
       }

       case 3:  // GameModule/PlayerService/viewLeaderboard
       {
         String $result = null;
         $result = this.viewLeaderboard ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // GameModule/PlayerService/getMaskedWord
       {
         String username = in.read_string ();
         String $result = null;
         $result = this.getMaskedWord (username);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }


  //server game state methods
       case 5:  // GameModule/PlayerService/getRoundTime
       {
         int $result = (int)0;
         $result = this.getRoundTime ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 6:  // GameModule/PlayerService/getWaitingTime
       {
         int $result = (int)0;
         $result = this.getWaitingTime ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 7:  // GameModule/PlayerService/getRemainingTime
       {
         String username = in.read_string ();
         int $result = (int)0;
         $result = this.getRemainingTime (username);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 8:  // GameModule/PlayerService/getIncorrectGuesses
       {
         String username = in.read_string ();
         int $result = (int)0;
         $result = this.getIncorrectGuesses (username);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 9:  // GameModule/PlayerService/endGameSession
       {
         String username = in.read_string ();
         this.endGameSession (username);
         out = $rh.createReply();
         break;
       }

       case 10:  // GameModule/PlayerService/getCurrentRound
       {
         String username = in.read_string ();
         int $result = (int)0;
         $result = this.getCurrentRound (username);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 11:  // GameModule/PlayerService/getPlayerWins
       {
         String username = in.read_string ();
         int $result = (int)0;
         $result = this.getPlayerWins (username);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 12:  // GameModule/PlayerService/startNewRound
       {
         String username = in.read_string ();
         GameModule.Bool $result = null;
         $result = this.startNewRound (username);
         out = $rh.createReply();
         GameModule.BoolHelper.write (out, $result);
         break;
       }

       case 13:  // GameModule/PlayerService/isRoundOver
       {
         String username = in.read_string ();
         GameModule.Bool $result = null;
         $result = this.isRoundOver (username);
         out = $rh.createReply();
         GameModule.BoolHelper.write (out, $result);
         break;
       }

       case 14:  // GameModule/PlayerService/isGameSessionOver
       {
         String username = in.read_string ();
         GameModule.Bool $result = null;
         $result = this.isGameSessionOver (username);
         out = $rh.createReply();
         GameModule.BoolHelper.write (out, $result);
         break;
       }

       case 15:  // GameModule/PlayerService/getGameSessionResult
       {
         String username = in.read_string ();
         String $result = null;
         $result = this.getGameSessionResult (username);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 16:  // GameModule/PlayerService/getGameState
       {
         String username = in.read_string ();
         GameModule.GameStateDTO $result = null;
         $result = this.getGameState (username);
         out = $rh.createReply();
         GameModule.GameStateDTOHelper.write (out, $result);
         break;
       }


  // Explicit cleanup after game session ends
       case 17:  // GameModule/PlayerService/cleanupPlayerSession
       {
         String username = in.read_string ();
         this.cleanupPlayerSession (username);
         out = $rh.createReply();
         break;
       }


  // Multiplayer mode
       case 18:  // GameModule/PlayerService/startMultiplayerGame
       {
         String username = in.read_string ();
         String $result = null;
         $result = this.startMultiplayerGame (username);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 19:  // GameModule/PlayerService/getMultiplayerLobbyState
       {
         String username = in.read_string ();
         String $result = null;
         $result = this.getMultiplayerLobbyState (username);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 20:  // GameModule/PlayerService/sendMultiplayerGuess
       {
         String username = in.read_string ();
         char letter = in.read_char ();
         GameModule.Bool $result = null;
         $result = this.sendMultiplayerGuess (username, letter);
         out = $rh.createReply();
         GameModule.BoolHelper.write (out, $result);
         break;
       }

       case 21:  // GameModule/PlayerService/startMultiplayerNextRound
       {
         String username = in.read_string ();
         GameModule.Bool $result = null;
         $result = this.startMultiplayerNextRound (username);
         out = $rh.createReply();
         GameModule.BoolHelper.write (out, $result);
         break;
       }


  // Match history (returns JSON)
       case 22:  // GameModule/PlayerService/getMatchHistory
       {
         String username = in.read_string ();
         String $result = null;
         $result = this.getMatchHistory (username);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 23:  // GameModule/PlayerService/getMatchDetails
       {
         String gameId = in.read_string ();
         String $result = null;
         $result = this.getMatchDetails (gameId);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }


  // Single Player Match History
       case 24:  // GameModule/PlayerService/getSinglePlayerMatchHistory
       {
         String username = in.read_string ();
         String $result = null;
         $result = this.getSinglePlayerMatchHistory (username);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 25:  // GameModule/PlayerService/getSinglePlayerMatchDetails
       {
         String gameId = in.read_string ();
         String $result = null;
         $result = this.getSinglePlayerMatchDetails (gameId);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }


  // Client signals ready after match found dialog for 1v1 and multiplayer
       case 26:  // GameModule/PlayerService/playerReadyForFirstRound
       {
         String username = in.read_string ();
         this.playerReadyForFirstRound (username);
         out = $rh.createReply();
         break;
       }

       case 27:  // GameModule/PlayerService/leaveMultiplayerGame
       {
         String username = in.read_string ();
         this.leaveMultiplayerGame (username);
         out = $rh.createReply();
         break;
       }


  // Read-only access to leaderboard data
       case 28:  // GameModule/PlayerService/getLeaderboardEntries
       {
         GameModule.LeaderboardEntryDTO $result[] = null;
         $result = this.getLeaderboardEntries ();
         out = $rh.createReply();
         GameModule.LeaderboardEntrySeqHelper.write (out, $result);
         break;
       }

       case 29:  // GameModule/CommonService/login
       {
         try {
           String username = in.read_string ();
           String password = in.read_string ();
           GameModule.Bool $result = null;
           $result = this.login (username, password);
           out = $rh.createReply();
           GameModule.BoolHelper.write (out, $result);
         } catch (GameModule.AlreadyLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           GameModule.AlreadyLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 30:  // GameModule/CommonService/logout
       {
         String username = in.read_string ();
         this.logout (username);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:GameModule/PlayerService:1.0", 
    "IDL:GameModule/CommonService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public PlayerService _this() 
  {
    return PlayerServiceHelper.narrow(
    super._this_object());
  }

  public PlayerService _this(org.omg.CORBA.ORB orb) 
  {
    return PlayerServiceHelper.narrow(
    super._this_object(orb));
  }


} // class PlayerServicePOA
