package GameModule;


/**
* GameModule/PlayerServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Monday, June 9, 2025 2:37:33 AM SGT
*/


// Player-specific functionality
public interface PlayerServiceOperations  extends GameModule.CommonServiceOperations
{
  String startGame (String username);
  GameModule.Bool sendGuess (String username, char letter);
  void finishRound (String username, int clientRemainingTime, GameModule.Bool guessedWord);
  String viewLeaderboard ();
  String getMaskedWord (String username);

  //server game state methods
  int getRoundTime ();
  int getWaitingTime ();
  int getRemainingTime (String username);
  int getIncorrectGuesses (String username);
  void endGameSession (String username);
  int getCurrentRound (String username);
  int getPlayerWins (String username);
  GameModule.Bool startNewRound (String username);
  GameModule.Bool isRoundOver (String username);
  GameModule.Bool isGameSessionOver (String username);
  String getGameSessionResult (String username);
  GameModule.GameStateDTO getGameState (String username);

  // Explicit cleanup after game session ends
  void cleanupPlayerSession (String username);

  // Multiplayer mode
  String startMultiplayerGame (String username);
  String getMultiplayerLobbyState (String username);
  GameModule.Bool sendMultiplayerGuess (String username, char letter);
  GameModule.Bool startMultiplayerNextRound (String username);

  // Match history (returns JSON)
  String getMatchHistory (String username);
  String getMatchDetails (String gameId);

  // Single Player Match History
  String getSinglePlayerMatchHistory (String username);
  String getSinglePlayerMatchDetails (String gameId);

  // Client signals ready after match found dialog for 1v1 and multiplayer
  void playerReadyForFirstRound (String username);
  void leaveMultiplayerGame (String username);

  // Read-only access to leaderboard data
  GameModule.LeaderboardEntryDTO[] getLeaderboardEntries ();
} // interface PlayerServiceOperations
