package GameModule;


/**
* GameModule/SystemStatisticsDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Thursday, May 15, 2025 9:07:00 AM SGT
*/

public final class SystemStatisticsDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int totalGames = (int)0;
  public int wins = (int)0;
  public int losses = (int)0;
  public double winRate = (double)0;
  public int waitingTime = (int)0;
  public int roundTime = (int)0;

  public SystemStatisticsDTO ()
  {
  } // ctor

  public SystemStatisticsDTO (int _totalGames, int _wins, int _losses, double _winRate, int _waitingTime, int _roundTime)
  {
    totalGames = _totalGames;
    wins = _wins;
    losses = _losses;
    winRate = _winRate;
    waitingTime = _waitingTime;
    roundTime = _roundTime;
  } // ctor

} // class SystemStatisticsDTO
