package GameModule;

/**
* GameModule/SystemStatisticsDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameService.idl
* Saturday, June 7, 2025 6:18:18 PM SGT
*/

public final class SystemStatisticsDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public GameModule.SystemStatisticsDTO value = null;

  public SystemStatisticsDTOHolder ()
  {
  }

  public SystemStatisticsDTOHolder (GameModule.SystemStatisticsDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameModule.SystemStatisticsDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameModule.SystemStatisticsDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameModule.SystemStatisticsDTOHelper.type ();
  }

}
