# DO NOT EDIT THIS FILE!
#
# Python module LoginModule__POA generated by omniidl

import omniORB
omniORB.updateModule("LoginModule__POA")

# ** 1. Stub files contributing to this module
import LoginService_idl

# ** 2. Sub-modules

# ** 3. End
