package AdminModule;


/**
* AdminModule/AdminService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/java/idl/AdminService.idl
* Monday, June 9, 2025 5:51:10 PM SGT
*/

public interface AdminService extends AdminServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AdminService
