package AdminModule;

/**
* AdminModule/AdminServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/java/idl/AdminService.idl
* Friday, June 27, 2025 9:12:47 PM CST
*/

public final class AdminServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public AdminModule.AdminService value = null;

  public AdminServiceHolder ()
  {
  }

  public AdminServiceHolder (AdminModule.AdminService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AdminModule.AdminServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AdminModule.AdminServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AdminModule.AdminServiceHelper.type ();
  }

}
