package AdminModule;


/**
* AdminModule/AdminServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/java/idl/AdminService.idl
* Friday, June 27, 2025 9:12:47 PM CST
*/

public interface AdminServiceOperations 
{

  // Admin player management
  AdminModule.Bool createPlayer (String username, String password);
  AdminModule.Bool deletePlayer (String username);
  AdminModule.Bool updatePlayerPassword (String username, String newPassword);
  AdminModule.Bool updatePlayerUsername (String username, String newUsername);
  AdminModule.Bool updatePlayerWins (String username, int wins);
  String viewPlayers ();

  // Admin system settings
  AdminModule.Bool updateSettings (int waitingTime, int roundTime);

  // Admin word management
  AdminModule.Bool addWord (String word);
  AdminModule.Bool updateWord (String oldWord, String newWord);
  AdminModule.Bool deleteWord (String word);
  String[] getAllWords ();

  // Admin statistics
  AdminModule.SystemStatisticsDTO getSystemStatistics ();
  AdminModule.LeaderboardEntryDTO[] getLeaderboardEntries ();

  // Match history admin view
  String getMatchHistory (String username);
  String getMatchDetails (String gameId);
  String getSinglePlayerMatchHistory (String username);
  String getSinglePlayerMatchDetails (String gameId);
} // interface AdminServiceOperations
