package AdminModule;


/**
* AdminModule/AdminService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AdminService.idl
* Saturday, June 14, 2025 7:10:25 PM SGT
*/

public interface AdminService extends AdminServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AdminService
