package AdminModule;


/**
* AdminModule/AdminService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/java/idl/AdminService.idl
* Friday, June 27, 2025 9:12:47 PM CST
*/

public interface AdminService extends AdminServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AdminService
