package AdminModule;


/**
* AdminModule/Bool.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/java/idl/AdminService.idl
* Monday, June 9, 2025 5:51:10 PM SGT
*/

public class Bool implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static AdminModule.Bool[] __array = new AdminModule.Bool [__size];

  public static final int _BOOL_FALSE = 0;
  public static final AdminModule.Bool BOOL_FALSE = new AdminModule.Bool(_BOOL_FALSE);
  public static final int _BOOL_TRUE = 1;
  public static final AdminModule.Bool BOOL_TRUE = new AdminModule.Bool(_BOOL_TRUE);

  public int value ()
  {
    return __value;
  }

  public static AdminModule.Bool from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected Bool (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class Bool
