package AdminModule;

/**
* AdminModule/BoolHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/java/idl/AdminService.idl
* Monday, June 9, 2025 5:51:10 PM SGT
*/

public final class BoolHolder implements org.omg.CORBA.portable.Streamable
{
  public AdminModule.Bool value = null;

  public BoolHolder ()
  {
  }

  public BoolHolder (AdminModule.Bool initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AdminModule.BoolHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AdminModule.BoolHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AdminModule.BoolHelper.type ();
  }

}
