package AdminModule;

/**
* AdminModule/LeaderboardEntryDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/java/idl/AdminService.idl
* Friday, June 27, 2025 9:12:47 PM CST
*/

public final class LeaderboardEntryDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public AdminModule.LeaderboardEntryDTO value = null;

  public LeaderboardEntryDTOHolder ()
  {
  }

  public LeaderboardEntryDTOHolder (AdminModule.LeaderboardEntryDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AdminModule.LeaderboardEntryDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AdminModule.LeaderboardEntryDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AdminModule.LeaderboardEntryDTOHelper.type ();
  }

}
