package AdminModule;


/**
* AdminModule/LeaderboardEntrySeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AdminService.idl
* Saturday, June 14, 2025 7:10:25 PM SGT
*/

public final class LeaderboardEntrySeqHolder implements org.omg.CORBA.portable.Streamable
{
  public AdminModule.LeaderboardEntryDTO value[] = null;

  public LeaderboardEntrySeqHolder ()
  {
  }

  public LeaderboardEntrySeqHolder (AdminModule.LeaderboardEntryDTO[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AdminModule.LeaderboardEntrySeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AdminModule.LeaderboardEntrySeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AdminModule.LeaderboardEntrySeqHelper.type ();
  }

}
