package AdminModule;


/**
* AdminModule/LeaderboardEntrySeqHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AdminService.idl
* Saturday, June 14, 2025 7:10:25 PM SGT
*/

abstract public class LeaderboardEntrySeqHelper
{
  private static String  _id = "IDL:AdminModule/LeaderboardEntrySeq:1.0";

  public static void insert (org.omg.CORBA.Any a, AdminModule.LeaderboardEntryDTO[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static AdminModule.LeaderboardEntryDTO[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = AdminModule.LeaderboardEntryDTOHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (AdminModule.LeaderboardEntrySeqHelper.id (), "LeaderboardEntrySeq", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static AdminModule.LeaderboardEntryDTO[] read (org.omg.CORBA.portable.InputStream istream)
  {
    AdminModule.LeaderboardEntryDTO value[] = null;
    int _len0 = istream.read_long ();
    value = new AdminModule.LeaderboardEntryDTO[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = AdminModule.LeaderboardEntryDTOHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, AdminModule.LeaderboardEntryDTO[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      AdminModule.LeaderboardEntryDTOHelper.write (ostream, value[_i0]);
  }

}
