package AdminModule;

/**
* AdminModule/SystemStatisticsDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AdminService.idl
* Saturday, June 14, 2025 7:10:25 PM SGT
*/

public final class SystemStatisticsDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public AdminModule.SystemStatisticsDTO value = null;

  public SystemStatisticsDTOHolder ()
  {
  }

  public SystemStatisticsDTOHolder (AdminModule.SystemStatisticsDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AdminModule.SystemStatisticsDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AdminModule.SystemStatisticsDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AdminModule.SystemStatisticsDTOHelper.type ();
  }

}
