package LoginModule;


/**
* LoginModule/_LoginServiceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/java/idl/LoginService.idl
* Friday, June 27, 2025 9:12:46 PM CST
*/

public class _LoginServiceStub extends org.omg.CORBA.portable.ObjectImpl implements LoginModule.LoginService
{

  public LoginModule.LoginResponse loginWithSession (String username, String password) throws LoginModule.AlreadyLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("loginWithSession", true);
                $out.write_string (username);
                $out.write_string (password);
                $in = _invoke ($out);
                LoginModule.LoginResponse $result = LoginModule.LoginResponseHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:LoginModule/AlreadyLoggedInException:1.0"))
                    throw LoginModule.AlreadyLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return loginWithSession (username, password        );
            } finally {
                _releaseReply ($in);
            }
  } // loginWithSession

  public LoginModule.Bool login (String username, String password) throws LoginModule.AlreadyLoggedInException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("login", true);
                $out.write_string (username);
                $out.write_string (password);
                $in = _invoke ($out);
                LoginModule.Bool $result = LoginModule.BoolHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:LoginModule/AlreadyLoggedInException:1.0"))
                    throw LoginModule.AlreadyLoggedInExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return login (username, password        );
            } finally {
                _releaseReply ($in);
            }
  } // login

  public void logout (String username)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("logout", true);
                $out.write_string (username);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                logout (username        );
            } finally {
                _releaseReply ($in);
            }
  } // logout

  public LoginModule.Bool createPlayer (String username, String password)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("createPlayer", true);
                $out.write_string (username);
                $out.write_string (password);
                $in = _invoke ($out);
                LoginModule.Bool $result = LoginModule.BoolHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return createPlayer (username, password        );
            } finally {
                _releaseReply ($in);
            }
  } // createPlayer

  public LoginModule.Bool validateSession (String username, String sessionId)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("validateSession", true);
                $out.write_string (username);
                $out.write_string (sessionId);
                $in = _invoke ($out);
                LoginModule.Bool $result = LoginModule.BoolHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return validateSession (username, sessionId        );
            } finally {
                _releaseReply ($in);
            }
  } // validateSession

  public LoginModule.Bool checkSessionValid (String username)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("checkSessionValid", true);
                $out.write_string (username);
                $in = _invoke ($out);
                LoginModule.Bool $result = LoginModule.BoolHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return checkSessionValid (username        );
            } finally {
                _releaseReply ($in);
            }
  } // checkSessionValid

  public LoginModule.Bool keepAlive (String username, String sessionId)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("keepAlive", true);
                $out.write_string (username);
                $out.write_string (sessionId);
                $in = _invoke ($out);
                LoginModule.Bool $result = LoginModule.BoolHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return keepAlive (username, sessionId        );
            } finally {
                _releaseReply ($in);
            }
  } // keepAlive

  public LoginModule.Bool isPlayerDeleted (String username)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("isPlayerDeleted", true);
                $out.write_string (username);
                $in = _invoke ($out);
                LoginModule.Bool $result = LoginModule.BoolHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return isPlayerDeleted (username        );
            } finally {
                _releaseReply ($in);
            }
  } // isPlayerDeleted

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:LoginModule/LoginService:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     com.sun.corba.se.impl.orbutil.IORCheckImpl.check(str, "LoginModule._LoginServiceStub");
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _LoginServiceStub
