package LoginModule;


/**
* LoginModule/AlreadyLoggedInException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/java/idl/LoginService.idl
* Friday, June 27, 2025 9:12:46 PM CST
*/

public final class AlreadyLoggedInException extends org.omg.CORBA.UserException
{
  public String message = null;

  public AlreadyLoggedInException ()
  {
    super(AlreadyLoggedInExceptionHelper.id());
  } // ctor

  public AlreadyLoggedInException (String _message)
  {
    super(AlreadyLoggedInExceptionHelper.id());
    message = _message;
  } // ctor


  public AlreadyLoggedInException (String $reason, String _message)
  {
    super(AlreadyLoggedInExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class AlreadyLoggedInException
