package LoginModule;

/**
* LoginModule/BoolHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/java/idl/LoginService.idl
* Friday, June 27, 2025 9:12:46 PM CST
*/

public final class BoolHolder implements org.omg.CORBA.portable.Streamable
{
  public LoginModule.Bool value = null;

  public BoolHolder ()
  {
  }

  public BoolHolder (LoginModule.Bool initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LoginModule.BoolHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LoginModule.BoolHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LoginModule.BoolHelper.type ();
  }

}
