package LoginModule;


/**
* LoginModule/BoolHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LoginService.idl
* Monday, June 16, 2025 5:46:09 PM SGT
*/

abstract public class BoolHelper
{
  private static String  _id = "IDL:LoginModule/Bool:1.0";

  public static void insert (org.omg.CORBA.Any a, LoginModule.Bool that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static LoginModule.Bool extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (LoginModule.BoolHelper.id (), "Bool", new String[] { "BOOL_FALSE", "BOOL_TRUE"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static LoginModule.Bool read (org.omg.CORBA.portable.InputStream istream)
  {
    return LoginModule.Bool.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, LoginModule.Bool value)
  {
    ostream.write_long (value.value ());
  }

}
