package LoginModule;


/**
* LoginModule/LoginServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LoginService.idl
* Monday, June 16, 2025 5:46:09 PM SGT
*/

public abstract class LoginServicePOA extends org.omg.PortableServer.Servant
 implements LoginModule.LoginServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("loginWithSession", new java.lang.Integer (0));
    _methods.put ("login", new java.lang.Integer (1));
    _methods.put ("logout", new java.lang.Integer (2));
    _methods.put ("createPlayer", new java.lang.Integer (3));
    _methods.put ("validateSession", new java.lang.Integer (4));
    _methods.put ("checkSessionValid", new java.lang.Integer (5));
    _methods.put ("keepAlive", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // LoginModule/LoginService/loginWithSession
       {
         try {
           String username = in.read_string ();
           String password = in.read_string ();
           LoginModule.LoginResponse $result = null;
           $result = this.loginWithSession (username, password);
           out = $rh.createReply();
           LoginModule.LoginResponseHelper.write (out, $result);
         } catch (LoginModule.AlreadyLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           LoginModule.AlreadyLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // LoginModule/LoginService/login
       {
         try {
           String username = in.read_string ();
           String password = in.read_string ();
           LoginModule.Bool $result = null;
           $result = this.login (username, password);
           out = $rh.createReply();
           LoginModule.BoolHelper.write (out, $result);
         } catch (LoginModule.AlreadyLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           LoginModule.AlreadyLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 2:  // LoginModule/LoginService/logout
       {
         String username = in.read_string ();
         this.logout (username);
         out = $rh.createReply();
         break;
       }

       case 3:  // LoginModule/LoginService/createPlayer
       {
         String username = in.read_string ();
         String password = in.read_string ();
         LoginModule.Bool $result = null;
         $result = this.createPlayer (username, password);
         out = $rh.createReply();
         LoginModule.BoolHelper.write (out, $result);
         break;
       }

       case 4:  // LoginModule/LoginService/validateSession
       {
         String username = in.read_string ();
         String sessionId = in.read_string ();
         LoginModule.Bool $result = null;
         $result = this.validateSession (username, sessionId);
         out = $rh.createReply();
         LoginModule.BoolHelper.write (out, $result);
         break;
       }

       case 5:  // LoginModule/LoginService/checkSessionValid
       {
         String username = in.read_string ();
         LoginModule.Bool $result = null;
         $result = this.checkSessionValid (username);
         out = $rh.createReply();
         LoginModule.BoolHelper.write (out, $result);
         break;
       }

       case 6:  // LoginModule/LoginService/keepAlive
       {
         String username = in.read_string ();
         String sessionId = in.read_string ();
         LoginModule.Bool $result = null;
         $result = this.keepAlive (username, sessionId);
         out = $rh.createReply();
         LoginModule.BoolHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:LoginModule/LoginService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public LoginService _this() 
  {
    return LoginServiceHelper.narrow(
    super._this_object());
  }

  public LoginService _this(org.omg.CORBA.ORB orb) 
  {
    return LoginServiceHelper.narrow(
    super._this_object(orb));
  }


} // class LoginServicePOA
