package LoginModule;


/**
* LoginModule/LoginResponse.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LoginService.idl
* Monday, June 16, 2025 5:46:09 PM SGT
*/

public final class LoginResponse implements org.omg.CORBA.portable.IDLEntity
{
  public LoginModule.Bool success = null;
  public String sessionId = null;

  public LoginResponse ()
  {
  } // ctor

  public LoginResponse (LoginModule.Bool _success, String _sessionId)
  {
    success = _success;
    sessionId = _sessionId;
  } // ctor

} // class LoginResponse
