package LoginModule;

/**
* LoginModule/LoginResponseHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/java/idl/LoginService.idl
* Friday, June 27, 2025 9:12:46 PM CST
*/

public final class LoginResponseHolder implements org.omg.CORBA.portable.Streamable
{
  public LoginModule.LoginResponse value = null;

  public LoginResponseHolder ()
  {
  }

  public LoginResponseHolder (LoginModule.LoginResponse initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LoginModule.LoginResponseHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LoginModule.LoginResponseHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LoginModule.LoginResponseHelper.type ();
  }

}
