package LoginModule;


/**
* LoginModule/LoginServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LoginService.idl
* Monday, June 16, 2025 5:46:09 PM SGT
*/

public interface LoginServiceOperations 
{
  LoginModule.LoginResponse loginWithSession (String username, String password) throws LoginModule.AlreadyLoggedInException;
  LoginModule.Bool login (String username, String password) throws LoginModule.AlreadyLoggedInException;
  void logout (String username);
  LoginModule.Bool createPlayer (String username, String password);
  LoginModule.Bool validateSession (String username, String sessionId);
  LoginModule.Bool checkSessionValid (String username);
  LoginModule.Bool keepAlive (String username, String sessionId);
} // interface LoginServiceOperations
