package LoginModule;

/**
* LoginModule/LoginServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LoginService.idl
* Monday, June 16, 2025 5:46:09 PM SGT
*/

public final class LoginServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public LoginModule.LoginService value = null;

  public LoginServiceHolder ()
  {
  }

  public LoginServiceHolder (LoginModule.LoginService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LoginModule.LoginServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LoginModule.LoginServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LoginModule.LoginServiceHelper.type ();
  }

}
